site_name: Sy_Blog&Notes
site_url: https://www.sy-study.top
plugins:
  - search
  - blog
theme: 
  # åº”ç”¨ä¸»é¢˜
  name: material
  # å­—ä½“
  font:
    text: Roboto
    code: Roboto Mono

  features:
  # å¯¼èˆªæ ğŸ§­
    - navigation.top
    - content.code.copy
    - content.code.select
    - navigation.tabs
  # ä¿®æ”¹é¢œè‰²
  palette:
  # æ˜äº®ä¸»é¢˜
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # æš—è‰²ä¸»é¢˜
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# markdownæ‰©å±•ï¼ˆä»£ç é«˜äº®ï¼‰
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # æ•°å­¦å…¬å¼
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css